### ISSUE TITLE
Doesn't work after the update

### ISSUE THREAD

**Issue by realdep** [yafyz/nitrsnip#19]
I've tried it both on AWS and local. I've updated to the latest commit while keeping my config and now it simply doesn't work.

After the output it doesnt receive anyting, doesnt update the webhook, doesnt do anything. The program is unresponsive.

sometimes its stuck here:
![image](https://user-images.githubusercontent.com/9782679/236627146-be6a4907-3a56-45d6-9953-ec102b1f1934.png)

sometimes here:
![image](https://user-images.githubusercontent.com/9782679/236627165-27d0d919-ea1a-4f6a-a395-7eaf375115f2.png)

But nothing follows after it.

I tried changing my token, enabling/disabling improve_latency, other config settings and etc. but nothing worked.
I've been using this for a year now and this is the first time this happened.

**Comment by yafyz** [comment]
i am aware, it's an old issue that sometimes shows up when either discord or cloudflare change something
the problem is that the http header parser gets stuck in an infinite loop when headers are split over multiple packets https://github.com/yafyz/nitrsnip/blob/5059e72c9330b4ec95f9953c4126e95d6cbb4bdf/http.js#L85-L93
it happened once already but only when sending stuff over webhooks so i just did a lazy patch to just use node https for that (https://github.com/yafyz/nitrsnip/commit/fb691be7db2a14289c2288cbdb97e69a56df83d5)

i dont think i actually use response headers anywhere so i guess imma just skip them cause i am too lazy to fix it properly

**Comment by yafyz** [comment]
seems fixed
fix doesn't actually remove header parsing, but it's still a hella lazy fix tho
