### ISSUE TITLE
What's the difference between latency and total time? and what is total time?

### ISSUE THREAD

**Issue by realdep** [yafyz/nitrsnip#4]
![Capture](https://user-images.githubusercontent.com/9782679/130631413-438953ad-b5b2-410f-8feb-7e8245522278.PNG)

pretty much

**Comment by yafyz** [comment]
yeah i forgot to add that into the readme
latency is what basically all snipers report, its the time between sending a request to claim the code and getting a response from the server
total time is time between message creation on discord servers and getting response from server for claim attempt
total time is not very accurate because your clock and the servers clock are not synchronized
